NAMS - Not Another MUD Server: SocketServer Class Reference
SocketServer Class Reference
#include <socketserver.h>
Public Member Functions
SocketServer (Server *server, const sint_t &descriptor)
~SocketServer ()
const void Accept ()
const bool Bind (const uint_t &port, const string &addr)
const void Delete ()
const bool Listen ()
const bool New ()
const bool Thread ()
Server * gServer () const
const bool sServer (Server *server)
Static Public Member Functions
static void * Update (void *data)
Private Attributes
Server * m_server
Detailed Description
Definition at line 23 of file socketserver.h.
Constructor & Destructor Documentation
SocketServer::SocketServer (Server * server, const sint_t & descriptor)
Definition at line 265 of file socketserver.cpp.
References Server::gSocketOpen(), m_server, socket_server_list, sServer(), Server::sSocketOpen(), and UFLAGS_DE.
                                                                     : Socket( server, descriptor )
{
    UFLAGS_DE( flags );
    sServer( server );
    m_server->sSocketOpen( m_server->gSocketOpen() + 1 );
    socket_server_list.push_back( this );
    return;
}
SocketServer::~SocketServer ()
Definition at line 277 of file socketserver.cpp.
References Thread::MutexUnlock().
{
    MutexUnlock();
    ::pthread_exit( reinterpret_cast<void*>( EXIT_SUCCESS ) );
    return;
}
Member Function Documentation
const void SocketServer::Accept ()
Definition at line 26 of file socketserver.cpp.
References SocketClient::Delete(), Socket::gDescriptor(), gServer(), LOGERRNO, LOGSTR, SocketClient::Thread(), UFLAGS_DE, and Socket::Valid().
Referenced by Update().
{
    UFLAGS_DE( flags );
    sint_t descriptor = 0;
    sockaddr_storage sin;
    socklen_t size = static_cast<socklen_t>( sizeof( sin ) );
    SocketClient* socket_client;
    if ( !Valid() )
    {
        LOGSTR( flags, "SocketServer::Accept()-> called with invalid socket" );
        return;
    }
    if ( ::getsockname( gDescriptor(), reinterpret_cast<sockaddr*>( &sin ), &size ) < 0 )
    {
        LOGERRNO( flags, "SocketServer::Accept()->getsockname()->" );
        return;
    }
    if ( ( descriptor = ::accept( gDescriptor(), reinterpret_cast<sockaddr*>( &sin ), &size ) ) < 0 )
    {
        LOGERRNO( flags, "SocketServer::Accept()->accept()->" );
        return;
    }
    socket_client = new SocketClient( gServer(), descriptor );
    if ( !socket_client->Thread() )
    {
        LOGSTR( flags, "SocketServer::Accept()->SocketClient::Thread()-> returned false" );
        socket_client->Delete();
        return;
    }
    return;
}
const bool SocketServer::Bind (const uint_t & port, const string & addr)
Definition at line 64 of file socketserver.cpp.
References CSTR, Socket::gDescriptor(), LOGERRNO, LOGSTR, UFLAGS_DE, and Socket::Valid().
Referenced by New().
{
    UFLAGS_DE( flags );
    sint_t enable = 1;
    static sockaddr_in6 sa_zero;
    sockaddr_in6 sa = sa_zero;
    if ( !Valid() )
    {
        LOGSTR( flags, "SocketServer::Bind()-> called with invalid socket" );
        return false;
    }
    if ( addr.empty() )
    {
        LOGSTR( flags, "SocketServer::Bind()-> called with empty addr" );
        return false;
    }
    sa.sin6_family = AF_INET6;
    sa.sin6_port = htons( port );
    inet_pton( AF_INET6, CSTR( addr ), &sa.sin6_addr );
    if ( ::setsockopt( gDescriptor(), SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<const char*>( &enable ), sizeof( enable ) ) < 0 )
    {
        LOGERRNO( flags, "SocketServer::Bind()->setsockopt()->" );
        return false;
    }
    if ( ::bind( gDescriptor(), reinterpret_cast<sockaddr*>( &sa ), sizeof( sa ) ) < 0 )
    {
        LOGERRNO( flags, "SocketServer::Bind()->bind()->" );
        return false;
    }
    return true;
}
const void SocketServer::Delete () [virtual]
Implements Socket.
Definition at line 102 of file socketserver.cpp.
References Server::gSocketClose(), LOGFMT, m_server, Thread::MutexLock(), socket_server_list, Server::sSocketClose(), UFLAGS_DE, and Socket::Valid().
Referenced by Update().
{
    UFLAGS_DE( flags );
    if ( !Valid() )
        return;
    MutexLock();
    if ( !m_server->sSocketClose( m_server->gSocketClose() + 1 ) )
        LOGFMT( flags, "SocketServer::Delete()->Server::sSocketClose()-> value %lu returned false", m_server->gSocketClose() + 1 );
    socket_server_list.remove( this );
    delete this;
    return;
}
Server* SocketServer::gServer () const [inline]
Definition at line 38 of file socketserver.h.
References m_server.
Referenced by Accept(), and Update().
{ return m_server; }
const bool SocketServer::Listen ()
Definition at line 120 of file socketserver.cpp.
References CFG_SOC_MAX_PENDING, Socket::gDescriptor(), LOGERRNO, LOGSTR, UFLAGS_DE, and Socket::Valid().
Referenced by New().
{
    UFLAGS_DE( flags );
    if ( !Valid() )
    {
        LOGSTR( flags, "SocketServer::Listen()-> called with invalid socket" );
        return false;
    }
    if ( ::listen( gDescriptor(), CFG_SOC_MAX_PENDING ) < 0 )
    {
        LOGERRNO( flags, "SocketServer::Listen()->listen()->" );
        return false;
    }
    return true;
}
const bool SocketServer::New () [virtual]
Implements Socket.
Definition at line 139 of file socketserver.cpp.
References Bind(), CSTR, Server::gHostname(), Server::gPort(), Listen(), LOGFMT, LOGSTR, m_server, Thread::MutexLock(), Thread::MutexUnlock(), Socket::sHostname(), Server::Shutdown(), and UFLAGS_DE.
Referenced by Thread().
{
    UFLAGS_DE( flags );
    MutexLock();
    if ( !Bind( m_server->gPort(), CFG_SOC_BIND_ADDR ) )
    {
        LOGSTR( flags, "SocketServer::New()->SocketServer::Bind()-> returned false" );
        m_server->Shutdown( EXIT_FAILURE );
    }
    if ( !sHostname( m_server->gHostname() ) )
    {
        LOGFMT( flags, "SocketServer::New()->SocketServer::sHostname()-> hostname %s returned false", CSTR( m_server->gHostname() ) );
        m_server->Shutdown( EXIT_FAILURE );
    }
    if ( !Listen() )
    {
        LOGSTR( flags, "SocketServer::New()->SocketServer::Listen()-> returned false" );
        m_server->Shutdown( EXIT_FAILURE );
    }
    MutexUnlock();
    return true;
}
const bool SocketServer::sServer (Server * server)
Definition at line 244 of file socketserver.cpp.
References LOGSTR, m_server, Server::Running(), and UFLAGS_DE.
Referenced by SocketServer().
{
    UFLAGS_DE( flags );
    if ( !server )
    {
        LOGSTR( flags, "SocketServer::sServer()-> called with NULL server" );
        return false;
    }
    if ( !server->Running() )
    {
        LOGSTR( flags, "SocketServer::sServer()-> called with offline server" );
        return false;
    }
    m_server = server;
    return true;
}
const bool SocketServer::Thread ()
Reimplemented from Thread.
Definition at line 168 of file socketserver.cpp.
References LOGERRNO, LOGSTR, New(), thread_list, UFLAGS_DE, Update(), and Socket::Valid().
Referenced by Server::Startup().
{
    UFLAGS_DE( flags );
    pthread_t thread_id = 0;
    pthread_attr_t res_attr;
    if ( !Valid() )
    {
        LOGSTR( flags, "SocketServer::Thread()-> called with invalid socket" );
        return false;
    }
    if ( !New() )
    {
        LOGSTR( flags, "SocketServer::Thread()->SocketServer::New()-> returned false" );
        return false;
    }
    if ( ::pthread_attr_init( &res_attr ) != 0 )
    {
        LOGERRNO( flags, "SocketServer::Thread()->pthread_attr_init()->" );
        return false;
    }
    if ( ::pthread_attr_setdetachstate( &res_attr, PTHREAD_CREATE_JOINABLE ) != 0 )
    {
        LOGERRNO( flags, "SocketServer::Thread()->pthread_attr_setdetachstate()->" );
        return false;
    }
    if ( ::pthread_create( &thread_id, &res_attr, &SocketServer::Update, this ) != 0 )
    {
        LOGERRNO( flags, "SocketServer::Thread()->pthread_create()->" );
        return false;
    }
    if ( ::pthread_attr_destroy( &res_attr ) != 0 )
    {
        LOGERRNO( flags, "SocketServer::Thread()->pthread_attr_destroy()->" );
        return false;
    }
    thread_list.insert( pair<pthread_t,string>( thread_id, "SocketServer::Thread()" ) );
    return true;
}
void * SocketServer::Update (void * data) [static]
Definition at line 215 of file socketserver.cpp.
References Accept(), Delete(), gServer(), LOGSTR, Server::Running(), UFLAGS_DE, USLEEP_MAX, and Socket::Valid().
Referenced by Thread().
{
    UFLAGS_DE( flags );
    SocketServer* socket_server = reinterpret_cast<SocketServer*>( data );
    if ( !socket_server->Valid() )
    {
        LOGSTR( flags, "SocketServer::Update()-> called with invalid socket" );
        socket_server->Delete();
    }
    for ( ;; )
    {
        // Look for new connections
        socket_server->Accept();
        if ( !socket_server->gServer()->Running() )
            break;
        ::usleep( USLEEP_MAX / CFG_GAM_PULSE_RATE );
    }
    socket_server->Delete();
    ::pthread_exit( reinterpret_cast<void*>( EXIT_SUCCESS ) );
}
Member Data Documentation
Server* SocketServer::m_server [private]
Definition at line 44 of file socketserver.h.
Referenced by Delete(), gServer(), New(), SocketServer(), and sServer().
The documentation for this class was generated from the following files:
h/socketserver.h
socketserver.cpp