NAMS - Not Another MUD Server: Thread Class Reference
Thread Class Reference
#include <thread.h>
Public Member Functions
Thread ()
~Thread ()
const void MutexLock ()
const void MutexUnlock ()
Private Attributes
pthread_mutex_t m_mutex
Detailed Description
Definition at line 21 of file thread.h.
Constructor & Destructor Documentation
Thread::Thread ()
Reimplemented in SocketClient, and SocketServer.
Definition at line 48 of file thread.cpp.
References LOGERRNO, m_mutex, and UFLAGS_DE.
{
    UFLAGS_DE( flags );
    if ( ::pthread_mutex_init( &m_mutex, NULL ) != 0 )
        LOGERRNO( flags, "Thread::Thread()->" );
    return;
}
Thread::~Thread ()
Definition at line 58 of file thread.cpp.
References LOGERRNO, m_mutex, and UFLAGS_DE.
{
    UFLAGS_DE( flags );
    if ( ::pthread_mutex_destroy( &m_mutex ) != 0 )
        LOGERRNO( flags, "Thread::~Thread()->" );
    return;
}
Member Function Documentation
const void Thread::MutexLock ()
Definition at line 24 of file thread.cpp.
References LOGERRNO, m_mutex, and UFLAGS_DE.
Referenced by SocketServer::Delete(), SocketClient::Delete(), SocketServer::New(), SocketClient::New(), and SocketClient::~SocketClient().
{
    UFLAGS_DE( flags );
    if ( ::pthread_mutex_trylock( &m_mutex ) != 0 )
        LOGERRNO( flags, "Thread::MutexLock()->" );
    return;
}
const void Thread::MutexUnlock ()
Definition at line 34 of file thread.cpp.
References LOGERRNO, m_mutex, and UFLAGS_DE.
Referenced by SocketServer::New(), and SocketServer::~SocketServer().
{
    UFLAGS_DE( flags );
    if ( ::pthread_mutex_unlock( &m_mutex ) != 0 )
        LOGERRNO( flags, "Thread::~Thread()->" );
    return;
}
Member Data Documentation
pthread_mutex_t Thread::m_mutex [private]
Definition at line 35 of file thread.h.
Referenced by MutexLock(), MutexUnlock(), Thread(), and ~Thread().
The documentation for this class was generated from the following files:
h/thread.h
thread.cpp