NAMS - Not Another MUD Server: Socket Class Reference
Socket Class Reference
#include <socket.h>
Public Member Functions
Socket (Server *server, const sint_t &descriptor)
~Socket ()
virtual const void Delete ()=0
virtual const bool New ()=0
const bool Valid () const
const uint_t gBytesRecvd () const
const uint_t gBytesSent () const
const sint_t gDescriptor () const
const string gHostname () const
const uint_t gPort () const
const bool sBytesRecvd (const uint_t &amount)
const bool sBytesSent (const uint_t &amount)
const bool sDescriptor (const sint_t &descriptor)
const bool sHostname (const string &hostname)
const bool sPort (const uint_t &port)
Private Attributes
uint_t m_bytes_recvd
uint_t m_bytes_sent
sint_t m_descriptor
string m_hostname
uint_t m_port
Detailed Description
Definition at line 23 of file socket.h.
Constructor & Destructor Documentation
Socket::Socket (Server * server, const sint_t & descriptor)
Definition at line 103 of file socket.cpp.
References m_bytes_recvd, m_bytes_sent, m_hostname, m_port, and sDescriptor().
{
    m_bytes_recvd = 0;
    m_bytes_sent = 0;
    sDescriptor( descriptor );
    m_hostname.clear();
    m_port = 0;
    return;
}
Socket::~Socket ()
Definition at line 114 of file socket.cpp.
References LOGERRNO, m_descriptor, and UFLAGS_DE.
{
    UFLAGS_DE( flags );
    if ( ::close( m_descriptor ) < 0 )
        LOGERRNO( flags, "Socket::~Socket()->close()->" );
    return;
}
Member Function Documentation
virtual const void Socket::Delete () [pure virtual]
Implemented in SocketClient, and SocketServer.
const uint_t Socket::gBytesRecvd () const [inline]
Definition at line 34 of file socket.h.
References m_bytes_recvd.
Referenced by SocketClient::Recv().
{ return m_bytes_recvd; }
const uint_t Socket::gBytesSent () const [inline]
Definition at line 35 of file socket.h.
References m_bytes_sent.
Referenced by SocketClient::Send().
{ return m_bytes_sent; }
const sint_t Socket::gDescriptor () const [inline]
Definition at line 36 of file socket.h.
References m_descriptor.
Referenced by SocketServer::Accept(), SocketServer::Bind(), SocketServer::Listen(), SocketClient::New(), SocketClient::ProcessCommand(), SocketClient::ProcessInput(), Server::ProcessInput(), SocketClient::QueueCommand(), SocketClient::Recv(), SocketClient::Send(), and SocketClient::Update().
{ return m_descriptor; }
const string Socket::gHostname () const [inline]
Definition at line 37 of file socket.h.
References m_hostname.
Referenced by SocketClient::New(), SocketClient::Recv(), and SocketClient::Send().
{ return m_hostname; }
const uint_t Socket::gPort () const [inline]
Definition at line 38 of file socket.h.
References m_port.
Referenced by SocketClient::New().
{ return m_port; }
virtual const bool Socket::New () [pure virtual]
Implemented in SocketClient, and SocketServer.
const bool Socket::sBytesRecvd (const uint_t & amount)
Definition at line 28 of file socket.cpp.
References LOGFMT, m_bytes_recvd, UFLAGS_DE, and uintmax_t.
Referenced by SocketClient::Recv().
{
    UFLAGS_DE( flags );
    if ( amount < 1 || ( ( m_bytes_recvd + amount ) >= uintmax_t ) )
    {
        LOGFMT( flags, "Socket::sBytesRecvd()-> called with m_bytes_recvd overflow: %lu + %lu", m_bytes_recvd, amount );
        return false;
    }
    m_bytes_recvd += amount;
    return true;
}
const bool Socket::sBytesSent (const uint_t & amount)
Definition at line 43 of file socket.cpp.
References LOGFMT, m_bytes_sent, UFLAGS_DE, and uintmax_t.
Referenced by SocketClient::Send().
{
    UFLAGS_DE( flags );
    if ( amount < 1 || ( ( m_bytes_sent + amount ) >= uintmax_t ) )
    {
        LOGFMT( flags, "Socket::sBytesSent()-> called with m_bytes_sent overflow: %lu + %lu", m_bytes_sent, amount );
        return false;
    }
    m_bytes_sent += amount;
    return true;
}
const bool Socket::sDescriptor (const sint_t & descriptor)
Definition at line 58 of file socket.cpp.
References LOGFMT, m_descriptor, sintmax_t, and UFLAGS_DE.
Referenced by Socket().
{
    UFLAGS_DE( flags );
    if ( descriptor < 0 || descriptor >= sintmax_t )
    {
        LOGFMT( flags, "Socket::sDescriptor()-> called with invalid descriptor: %ld", descriptor );
        return false;
    }
    m_descriptor = descriptor;
    return true;
}
const bool Socket::sHostname (const string & hostname)
Definition at line 73 of file socket.cpp.
References LOGSTR, m_hostname, and UFLAGS_DE.
Referenced by SocketServer::New(), and SocketClient::New().
{
    UFLAGS_DE( flags );
    if ( hostname.empty() )
    {
        LOGSTR( flags, "Socket::sHostname()-> called with empty hostname" );
        return false;
    }
    m_hostname = hostname;
    return true;
}
const bool Socket::sPort (const uint_t & port)
Definition at line 88 of file socket.cpp.
References LOGFMT, m_port, UFLAGS_DE, and uintmax_t.
Referenced by SocketClient::New().
{
    UFLAGS_DE( flags );
    if ( port <= uintmin_t || port >= uintmax_t )
    {
        LOGFMT( flags, "Socket::sPort()-> called with invalid port: %lu", port );
        return false;
    }
    m_port = port;
    return true;
}
const bool Socket::Valid () const [inline]
Definition at line 31 of file socket.h.
References m_descriptor.
Referenced by SocketServer::Accept(), SocketServer::Bind(), SocketServer::Delete(), SocketClient::Delete(), SocketServer::Listen(), SocketClient::ProcessCommand(), SocketClient::ProcessInput(), SocketClient::QueueCommand(), SocketClient::Recv(), SocketClient::Send(), SocketServer::Thread(), SocketClient::Thread(), SocketServer::Update(), and SocketClient::Update().
{ return m_descriptor > 0; }
Member Data Documentation
uint_t Socket::m_bytes_recvd [private]
Definition at line 48 of file socket.h.
Referenced by gBytesRecvd(), sBytesRecvd(), and Socket().
uint_t Socket::m_bytes_sent [private]
Definition at line 49 of file socket.h.
Referenced by gBytesSent(), sBytesSent(), and Socket().
sint_t Socket::m_descriptor [private]
Definition at line 50 of file socket.h.
Referenced by gDescriptor(), sDescriptor(), Valid(), and ~Socket().
string Socket::m_hostname [private]
Definition at line 51 of file socket.h.
Referenced by gHostname(), sHostname(), and Socket().
uint_t Socket::m_port [private]
Definition at line 52 of file socket.h.
Referenced by gPort(), Socket(), and sPort().
The documentation for this class was generated from the following files:
h/socket.h
socket.cpp