NAMS - Not Another MUD Server: SocketClient Class Reference
SocketClient Class Reference
#include <socketclient.h>
Public Member Functions
SocketClient (Server *server, const sint_t &descriptor)
~SocketClient ()
const void Delete ()
const bool New ()
const bool PendingOutput () const
const bool ProcessCommand ()
const bool ProcessInput ()
const bool QueueCommand (const string &command)
const bool Recv ()
const bool Send (const string &msg)
const bool Send ()
const bool Thread ()
const uint_t gIdle () const
Server * gServer () const
const uint_t gState () const
const bool sIdle (const uint_t &idle)
const bool sServer (Server *server)
const bool sState (const uint_t &state)
Static Public Member Functions
static void * Update (void *data)
Private Attributes
vector< string > m_command_queue
uint_t m_idle
string m_input
string m_output
Server * m_server
uint_t m_state
Detailed Description
Definition at line 26 of file socketclient.h.
Constructor & Destructor Documentation
SocketClient::SocketClient (Server * server, const sint_t & descriptor)
Definition at line 480 of file socketclient.cpp.
References Server::gSocketOpen(), m_command_queue, m_idle, m_input, m_output, m_server, m_state, socket_client_list, sServer(), and Server::sSocketOpen().
                                                                     : Socket( server, descriptor )
{
    m_command_queue.clear();
    m_idle = 0;
    m_input.clear();
    m_output.clear();
    sServer( server );
    m_state = SOC_STATE_DISCONNECTED;
    m_server->sSocketOpen( m_server->gSocketOpen() + 1 );
    socket_client_list.push_back( this );
    return;
}
SocketClient::~SocketClient ()
Definition at line 495 of file socketclient.cpp.
References Thread::MutexLock().
{
    MutexLock();
    ::pthread_exit( reinterpret_cast<void*>( EXIT_SUCCESS ) );
    return;
}
Member Function Documentation
const void SocketClient::Delete () [virtual]
Implements Socket.
Definition at line 24 of file socketclient.cpp.
References Server::gSocketClose(), LOGFMT, m_server, Thread::MutexLock(), socket_client_list, Server::sSocketClose(), UFLAGS_DE, and Socket::Valid().
Referenced by SocketServer::Accept(), New(), Server::ProcessInput(), and Update().
{
    UFLAGS_DE( flags );
    if ( !Valid() )
        return;
    MutexLock();
    if ( !m_server->sSocketClose( m_server->gSocketClose() + 1 ) )
        LOGFMT( flags, "SocketClient::Delete()->Server::sSocketClose()-> value %lu returned false", m_server->gSocketClose() + 1 );
    socket_client_list.remove( this );
    delete this;
    return;
}
const uint_t SocketClient::gIdle () const [inline]
Definition at line 45 of file socketclient.h.
References m_idle.
Referenced by Update().
{ return m_idle; }
Server* SocketClient::gServer () const [inline]
Definition at line 46 of file socketclient.h.
References m_server.
Referenced by ProcessCommand(), and Update().
{ return m_server; }
const uint_t SocketClient::gState () const [inline]
Definition at line 47 of file socketclient.h.
References m_state.
{ return m_state; }
const bool SocketClient::New () [virtual]
Implements Socket.
Definition at line 42 of file socketclient.cpp.
References CFG_STR_LOGIN, CSTR, Delete(), Socket::gDescriptor(), Socket::gHostname(), Socket::gPort(), LOGERRNO, LOGFMT, LOGSTR, Thread::MutexLock(), Send(), Socket::sHostname(), SOC_STATE_LOGIN_SCREEN, Socket::sPort(), sState(), and UFLAGS_DE.
Referenced by Thread().
{
    UFLAGS_DE( flags );
    sint_t error = 0;
    sockaddr_storage sin;
    socklen_t size = static_cast<socklen_t>( sizeof( sin ) );
    char hostname[CFG_STR_MAX_BUFLEN], service[CFG_STR_MAX_BUFLEN];
    MutexLock();
    if ( ::fcntl( gDescriptor(), F_SETFL, O_NONBLOCK ) < 0 )
    {
        LOGERRNO( flags, "SocketClient::New()->fcntl()->" );
        return false;
    }
    if ( ::getpeername( gDescriptor(), reinterpret_cast<sockaddr*>( &sin ), &size ) < 0 )
    {
        LOGERRNO( flags, "SocketClient::New()->getpeername()->" );
        if ( !sHostname( "(unknown)" ) )
        {
            LOGSTR( flags, "SocketClient::New()->SocketClient::sHostname()-> hostname (unknown) returned false" );
            Delete();
            return false;
        }
    }
    else
    {
        if ( ( error = ::getnameinfo( reinterpret_cast<sockaddr*>( &sin ), size, hostname, sizeof( hostname ), service, sizeof( service ), NI_NUMERICSERV) ) != 0 )
        {
            LOGFMT( flags, "SocketClient::New()->getnameinfo()-> returned errno %d:%s", error, gai_strerror( error ) );
            Delete();
            return false;
        }
        if ( !sHostname( hostname ) )
        {
            LOGFMT( flags, "SocketClient::New()->SocketClient::sHostname()-> hostname %s returned false", hostname );
            Delete();
            return false;
        }
        if ( !sPort( atol( service ) ) )
        {
            LOGFMT( flags, "SocketClient::New()->SocketClient::sPort()-> port %lu returned false", atol( service ) );
            Delete();
            return false;
        }
        LOGFMT( 0, "SocketClient::New()-> %s:%lu (%lu)", CSTR( gHostname() ), gPort(), gDescriptor() );
    }
    // negotiate telopts, send login message
    if ( !Send( CFG_STR_LOGIN ) )
    {
        LOGSTR( flags, "SocketClient::New()->SocketClient::Send()-> msg CFG_STR_LOGIN returned false" );
        Delete();
        return false;
    }
    if ( !sState( SOC_STATE_LOGIN_SCREEN ) )
    {
        LOGFMT( flags, "SocketClient::New()->SocketClient::sState()-> state %lu returned false", SOC_STATE_LOGIN_SCREEN );
        Delete();
        return false;
    }
    MutexLock();
    return true;
}
const bool SocketClient::PendingOutput () const [inline]
Definition at line 34 of file socketclient.h.
References m_output.
{ return !m_output.empty(); }
const bool SocketClient::ProcessCommand ()
Definition at line 115 of file socketclient.cpp.
References CRLF, Socket::gDescriptor(), gServer(), ITER, LOGFMT, m_command_queue, Send(), Server::Shutdown(), UFLAGS_DE, and Socket::Valid().
Referenced by Server::ProcessInput().
{
    UFLAGS_DE( flags );
    ITER( vector, string, vi );
    ITER( vector, string, vi_next );
    string cmd;
    if ( !Valid() )
    {
        LOGFMT( flags, "SocketClient::ProcessCommand()->SocketClient::Valid()-> descriptor %ld returned false", gDescriptor() );
        return false;
    }
    // Nothing new to process; move along
    if ( m_command_queue.empty() )
        return true;
    for ( vi = m_command_queue.begin(); vi != m_command_queue.end(); vi = vi_next )
    {
        cmd = *vi;
        vi_next = m_command_queue.erase( vi );
        if ( cmd.compare( "shutdown" ) == 0 )
            gServer()->Shutdown( EXIT_SUCCESS );
        else
        {
            Send( cmd );
            Send( CRLF );
        }
    }
    return true;
}
const bool SocketClient::ProcessInput ()
Definition at line 149 of file socketclient.cpp.
References CSTR, Socket::gDescriptor(), ITER, LOGFMT, m_input, QueueCommand(), Utils::StrNewlines(), UFLAGS_DE, and Socket::Valid().
Referenced by Update().
{
    UFLAGS_DE( flags );
    vector<string> commands;
    string command;
    ITER( vector, string, vi );
    if ( !Valid() )
    {
        LOGFMT( flags, "SocketClient::ProcessInput()->SocketClient::Valid()-> descriptor %ld returned false", gDescriptor() );
        return false;
    }
    // Nothing new to process; move along
    if ( m_input.empty() )
        return true;
    commands = Utils::StrNewlines( m_input );
    for ( vi = commands.begin(); vi != commands.end(); vi++ )
    {
        command = *vi;
        if ( !QueueCommand( command ) )
        {
            LOGFMT( flags, "SocketClient::ProcessInput()->SocketClient::QueueCommand()-> command %s returned false", CSTR( command ) );
            return false;
        }
    }
    m_input.clear();
    return true;
}
const bool SocketClient::QueueCommand (const string & command)
Definition at line 182 of file socketclient.cpp.
References Socket::gDescriptor(), LOGFMT, m_command_queue, UFLAGS_DE, and Socket::Valid().
Referenced by ProcessInput().
{
    UFLAGS_DE( flags );
    if ( !Valid() )
    {
        LOGFMT( flags, "SocketClient::QueueCommand()->SocketClient::Valid()-> descriptor %ld returned false", gDescriptor() );
        return false;
    }
    m_command_queue.push_back( command );
    return true;
}
const bool SocketClient::Recv ()
Definition at line 197 of file socketclient.cpp.
References CFG_STR_MAX_BUFLEN, CSTR, Socket::gBytesRecvd(), Socket::gDescriptor(), Socket::gHostname(), Server::gSocket(), LOGERRNO, LOGFMT, LOGSTR, m_input, m_server, Socket::sBytesRecvd(), sIdle(), UFLAGS_DE, and Socket::Valid().
Referenced by Update().
{
    UFLAGS_DE( flags );
    ssize_t amount = 0;
    char buf[CFG_STR_MAX_BUFLEN] = {'\0'};
    if ( !Valid() )
    {
        LOGFMT( flags, "SocketClient::Recv()->SocketClient::Valid()-> descriptor %ld returned false", gDescriptor() );
        return false;
    }
    if ( ( m_input.length() + CFG_STR_MAX_BUFLEN ) >= m_input.max_size() )
    {
        LOGFMT( flags, "SocketClient::Recv()-> called with m_input overflow: %lu + %lu", m_input.length(), CFG_STR_MAX_BUFLEN );
        return false;
    }
    if ( ( amount = ::recv( gDescriptor(), buf, CFG_STR_MAX_BUFLEN - 1, 0 ) ) < 1 )
    {
        if ( amount == 0 )
        {
            LOGFMT( flags, "SocketClient::Recv()->recv()-> broken pipe encountered on recv from: %s", CSTR( gHostname() ) );
            return false;
        }
        else if ( errno != EAGAIN && errno != EWOULDBLOCK )
        {
            LOGERRNO( flags, "SocketClient::Recv()->recv()->" );
            return false;
        }
        else
            return true;
    }
    if ( !m_server->gSocket()->sBytesRecvd( m_server->gSocket()->gBytesRecvd() + amount ) )
    {
        LOGFMT( flags, "SocketClient::Recv()->Server::gSocket()->Server::sBytesRecvd()-> value %lu returned false", m_server->gSocket()->gBytesRecvd() + amount );
        return false;
    }
    if ( !sBytesRecvd( gBytesRecvd() + amount ) )
    {
        LOGFMT( flags, "SocketClient::Recv()->SocketClient::sBytesRecvd()-> value %lu returned false", gBytesRecvd() + amount );
        return false;
    }
    if ( !sIdle( 0 ) )
    {
        LOGSTR( flags, "SocketClient::Recv()->SocketClient::sIdle()-> value 0 returned false" );
        return false;
    }
    m_input += buf;
    return true;
}
const bool SocketClient::Send (const string & msg)
Definition at line 254 of file socketclient.cpp.
References Socket::gDescriptor(), LOGFMT, m_output, m_state, UFLAGS_DE, and Socket::Valid().
Referenced by Update().
{
    UFLAGS_DE( flags );
    if ( !Valid() )
    {
        LOGFMT( flags, "SocketClient::Send()->SocketClient::Valid()-> descriptor %ld returned false", gDescriptor() );
        return false;
    }
    // Prepend a CRLF to ensure output lands on a newline.
    // Make this client configurable in the future.
    if ( m_output.empty() && m_state > SOC_STATE_LOGIN_SCREEN )
    {
        m_output += CRLF;
        m_output += msg;
    }
    else
        m_output += msg;
    return true;
}
const bool SocketClient::Send ()
Definition at line 277 of file socketclient.cpp.
References CSTR, Socket::gBytesSent(), Socket::gDescriptor(), Socket::gHostname(), Server::gSocket(), LOGERRNO, LOGFMT, m_output, m_server, Socket::sBytesSent(), UFLAGS_DE, and Socket::Valid().
Referenced by New(), and ProcessCommand().
{
    UFLAGS_DE( flags );
    ssize_t amount = 0;
    if ( !Valid() )
    {
        LOGFMT( flags, "SocketClient::Send()->SocketClient::Valid()-> descriptor %ld returned false", gDescriptor() );
        return false;
    }
    // Nothing new to process; move along
    if ( m_output.empty() )
        return true;
    if ( ( amount = ::send( gDescriptor(), CSTR( m_output ), m_output.length(), 0 ) ) < 1 )
    {
        if ( amount == 0 )
        {
            LOGFMT( flags, "SocketClient::Send()->send()-> broken pipe encountered on send to: %s", CSTR( gHostname() ) );
            return false;
        }
        else if ( errno != EAGAIN && errno != EWOULDBLOCK )
        {
            LOGERRNO( flags, "SocketClient::Send()->send()->" );
            return false;
        }
    }
    if ( !m_server->gSocket()->sBytesSent( m_server->gSocket()->gBytesSent() + amount ) )
    {
        LOGFMT( flags, "SocketClient::Send()->Server::gSocket()->Server::sBytesSent()-> value %lu returned false", m_server->gSocket()->gBytesSent() + amount );
        return false;
    }
    if ( !sBytesSent( gBytesSent() + amount ) )
    {
        LOGFMT( flags, "SocketClient::Send()->SocketClient::sBytesSent()-> value %lu returned false", gBytesSent() + amount );
        return false;
    }
    m_output.clear();
    return true;
}
const bool SocketClient::sIdle (const uint_t & idle)
Definition at line 429 of file socketclient.cpp.
References CFG_SOC_MAX_IDLE, LOGFMT, m_idle, and UFLAGS_DE.
Referenced by Recv(), and Update().
{
    UFLAGS_DE( flags );
    if ( idle < 0 || idle > CFG_SOC_MAX_IDLE )
    {
        LOGFMT( flags, "SocketClient::sIdle()-> called with invalid idle: %lu", idle );
        return false;
    }
    m_idle = idle;
    return true;
}
const bool SocketClient::sServer (Server * server)
Definition at line 444 of file socketclient.cpp.
References LOGSTR, m_server, Server::Running(), and UFLAGS_DE.
Referenced by SocketClient().
{
    UFLAGS_DE( flags );
    if ( !server )
    {
        LOGSTR( flags, "SocketClient::sServer()-> called with NULL server" );
        return false;
    }
    if ( !server->Running() )
    {
        LOGSTR( flags, "SocketClient::sServer()-> called with offline server" );
        return false;
    }
    m_server = server;
    return true;
}
const bool SocketClient::sState (const uint_t & state)
Definition at line 465 of file socketclient.cpp.
References LOGFMT, m_state, MAX_SOC_STATE, and UFLAGS_DE.
Referenced by New().
{
    UFLAGS_DE( flags );
    if ( state < SOC_STATE_DISCONNECTED || state >= MAX_SOC_STATE )
    {
        LOGFMT( flags, "SocketClient::sState()-> called with invalid state: %lu", state );
        return false;
    }
    m_state = state;
    return true;
}
const bool SocketClient::Thread ()
Reimplemented from Thread.
Definition at line 323 of file socketclient.cpp.
References LOGERRNO, LOGSTR, New(), thread_list, UFLAGS_DE, Update(), and Socket::Valid().
Referenced by SocketServer::Accept().
{
    UFLAGS_DE( flags );
    pthread_t thread_id = 0;
    pthread_attr_t res_attr;
    if ( !Valid() )
    {
        LOGSTR( flags, "SocketClient::Thread()-> called with invalid socket" );
        return false;
    }
    if ( !New() )
    {
        LOGSTR( flags, "SocketClient::Thread()->SocketClient::Newd()-> returned false" );
        return false;
    }
    if ( ::pthread_attr_init( &res_attr ) != 0 )
    {
        LOGERRNO( flags, "SocketClient::Thread()->pthread_attr_init()->" );
        return false;
    }
    if ( ::pthread_attr_setdetachstate( &res_attr, PTHREAD_CREATE_JOINABLE ) != 0 )
    {
        LOGERRNO( flags, "SocketClient::Thread()->pthread_attr_setdetachstate()->" );
        return false;
    }
    if ( ::pthread_create( &thread_id, &res_attr, &SocketClient::Update, this ) != 0 )
    {
        LOGERRNO( flags, "SocketClient::Thread()->pthread_create()->" );
        return false;
    }
    if ( ::pthread_attr_destroy( &res_attr ) != 0 )
    {
        LOGERRNO( flags, "SocketClient::Thread()->pthread_attr_destroy()->" );
        return false;
    }
    thread_list.insert( pair<pthread_t,string>( thread_id, "SocketClient::Thread()" ) );
    return true;
}
void * SocketClient::Update (void * data) [static]
Definition at line 370 of file socketclient.cpp.
References CFG_STR_IDLE, Delete(), Socket::gDescriptor(), gIdle(), gServer(), LOGFMT, LOGSTR, ProcessInput(), Recv(), Server::Running(), Send(), sIdle(), UFLAGS_DE, USLEEP_MAX, and Socket::Valid().
Referenced by Thread().
{
    UFLAGS_DE( flags );
    SocketClient* socket_client = reinterpret_cast<SocketClient*>( data );
    if ( !socket_client->Valid() )
    {
        LOGSTR( flags, "SocketClient::Update()-> called with invalid socket" );
        socket_client->Delete();
    }
    for ( ;; )
    {
        if ( !socket_client->sIdle( socket_client->gIdle() + 1 ) )
        {
            LOGFMT( flags, "SocketClient::Update()->SocketClient::sIdle()-> descriptor %ld returned false setting idle: %lu", socket_client->gDescriptor(), socket_client->gIdle() + 1 );
            socket_client->Delete();
        }
        // Disconnect sockets that have been idle for too long
        if ( socket_client->gIdle() >= CFG_SOC_MAX_IDLE )
        {
            LOGFMT( flags, "SocketClient::Update()->SocketClient::gIdle()-> disconnecting idle descriptor: %ld", socket_client->gDescriptor() );
            socket_client->Send( CFG_STR_IDLE );
            socket_client->Delete();
        }
        // Read input, save game character and disconnect socket if unable to
        if ( !socket_client->Recv() )
        {
            LOGFMT( flags, "SocketClient::Update()->SocketClient::Recv()-> descriptor %ld returned false", socket_client->gDescriptor() );
            socket_client->Delete();
        }
        if ( !socket_client->ProcessInput() )
        {
            LOGFMT( flags, "SocketClient::Update()->SocketClient::ProcessInput()-> descriptor %ld returned false", socket_client->gDescriptor() );
            socket_client->Delete();
        }
        if ( !socket_client->Send() )
        {
            LOGFMT( flags, "SocketClient::Update()->SocketClient::Send()-> descriptor %ld returned false", socket_client->gDescriptor() );
            socket_client->Delete();
        }
        if ( !socket_client->gServer()->Running() )
            break;
        ::usleep( USLEEP_MAX / CFG_GAM_PULSE_RATE );
    }
    socket_client->Delete();
    ::pthread_exit( reinterpret_cast<void*>( EXIT_SUCCESS ) );
}
Member Data Documentation
vector<string> SocketClient::m_command_queue [private]
Definition at line 55 of file socketclient.h.
Referenced by ProcessCommand(), QueueCommand(), and SocketClient().
uint_t SocketClient::m_idle [private]
Definition at line 56 of file socketclient.h.
Referenced by gIdle(), sIdle(), and SocketClient().
string SocketClient::m_input [private]
Definition at line 57 of file socketclient.h.
Referenced by ProcessInput(), Recv(), and SocketClient().
string SocketClient::m_output [private]
Definition at line 58 of file socketclient.h.
Referenced by PendingOutput(), Send(), and SocketClient().
Server* SocketClient::m_server [private]
Definition at line 59 of file socketclient.h.
Referenced by Delete(), gServer(), Recv(), Send(), SocketClient(), and sServer().
uint_t SocketClient::m_state [private]
Definition at line 60 of file socketclient.h.
Referenced by gState(), Send(), SocketClient(), and sState().
The documentation for this class was generated from the following files:
h/socketclient.h
socketclient.cpp