NAMS - Not Another MUD Server: Command Class Reference
Command Class Reference
#include <command.h>
Public Member Functions
Command ()
~Command ()
const bool Load (const string &file)
const void Unload ()
Private Attributes
uint_t m_level
string m_name
bool m_preempt
Detailed Description
Definition at line 23 of file command.h.
Constructor & Destructor Documentation
Command::Command ()
Definition at line 82 of file command.cpp.
References m_level, m_name, and m_preempt.
{
    m_level = 0;
    m_name.clear();
    m_preempt = false;
    return;
}
Command::~Command ()
Definition at line 91 of file command.cpp.
{
    return;
}
Member Function Documentation
const bool Command::Load (const string & file)
Definition at line 25 of file command.cpp.
References CFG_DAT_DIR_COMMAND, command_list, CSTR, Utils::DirPath(), Utils::iFile(), Utils::KeySet(), Utils::KeyValue(), LOGFMT, m_level, m_name, m_preempt, and UFLAGS_DE.
Referenced by Server::LoadCommands().
{
    UFLAGS_DE( flags );
    string path(  Utils::DirPath( CFG_DAT_DIR_COMMAND, file ) );
    string line, key, value;
    bool found = false;
    ifstream cmd;
    // Ensure there is a valid file to open
    if ( !Utils::iFile( path ) )
    {
        LOGFMT( flags, "Command::Load()->Utils::iFile()-> returned false for path: %s", CSTR( path ) );
        return false;
    }
    cmd.open( CSTR( path ), ifstream::in );
    while( cmd.is_open() && cmd.good() && getline( cmd, line ) )
    {
        // Find the key = value split
        if ( !Utils::KeyValue( key, value, line ) )
        {
            LOGFMT( flags, "Command::Load()->getline()-> invalid line format: %s", CSTR( line ) );
            continue;
        }
        // If the contents of arg3 == arg4 then assign arg5 == arg6
        for ( ;; )
        {
            found = false;
            Utils::KeySet( true, found, key, "Level",   value, m_level   );
            Utils::KeySet( true, found, key, "Name",    value, m_name    );
            Utils::KeySet( true, found, key, "Preempt", value, m_preempt );
            if ( !found )
                LOGFMT( flags, "Command::Load()->Utils::KeySet()-> key not found: %s", CSTR( key ) );
            break;
        }
    }
    command_list.insert( pair<const char,Command*>( m_name[0], this ) );
    return true;
}
const void Command::Unload ()
Definition at line 71 of file command.cpp.
{
    delete this;
   return;
}
Member Data Documentation
uint_t Command::m_level [private]
Definition at line 37 of file command.h.
Referenced by Command(), and Load().
string Command::m_name [private]
Definition at line 38 of file command.h.
Referenced by Command(), and Load().
bool Command::m_preempt [private]
Definition at line 39 of file command.h.
Referenced by Command(), and Load().
The documentation for this class was generated from the following files:
h/command.h
command.cpp