NAMS - Not Another MUD Server: Server Class Reference
Server Class Reference
#include <server.h>
Public Member Functions
Server ()
~Server ()
const bool LoadCommands ()
const bool ProcessInput ()
const bool Running () const
const void Startup ()
const void Shutdown (const sint_t &status)
const void Update ()
const string gHostname () const
const uint_t gPort () const
SocketServer * gSocket () const
const uint_t gSocketClose () const
const uint_t gSocketOpen () const
const string gStatus () const
const bool sPort (const uint_t &port)
const bool sSocketClose (const uint_t &amount)
const bool sSocketOpen (const uint_t &amount)
Private Member Functions
ITER (list, SocketClient *, m_socket_client_next)
Private Attributes
uint_t m_dir_close
uint_t m_dir_open
uint_t m_port
bool m_shutdown
SocketServer * m_socket
uint_t m_socket_close
uint_t m_socket_open
timeval m_time_boot
timeval m_time_current
Detailed Description
Definition at line 27 of file server.h.
Constructor & Destructor Documentation
Server::Server ()
Definition at line 264 of file server.cpp.
References m_dir_close, m_dir_open, m_port, m_shutdown, m_socket, m_socket_close, m_socket_open, m_time_boot, m_time_current, and socket_client_list.
{
    m_dir_close = 0;
    m_dir_open = 0;
    m_port = 0;
    m_shutdown = true;
    m_socket = 0;
    m_socket_client_next = socket_client_list.begin();
    m_socket_close = 0;
    m_socket_open = 0;
    m_time_boot = timeval();
    m_time_current = timeval();
    return;
}
Server::~Server ()
Definition at line 280 of file server.cpp.
{
    return;
}
Member Function Documentation
const string Server::gHostname () const
Definition at line 194 of file server.cpp.
References CFG_STR_MAX_BUFLEN, LOGERRNO, and UFLAGS_DE.
Referenced by SocketServer::New().
{
    UFLAGS_DE( flags );
    string output;
    char hostname[CFG_STR_MAX_BUFLEN] = {'\0'};
    if ( ::gethostname( hostname, CFG_STR_MAX_BUFLEN - 1 ) < 0 )
    {
        LOGERRNO( flags, "Server::gHostname()->gethostname()->" );
        output = "(unknown)";
        return output;
    }
    output = hostname;
    return output;
}
const uint_t Server::gPort () const [inline]
Definition at line 42 of file server.h.
References m_port.
Referenced by SocketServer::New().
{ return m_port; }
SocketServer* Server::gSocket () const [inline]
Definition at line 43 of file server.h.
References m_socket.
Referenced by SocketClient::Recv(), and SocketClient::Send().
{ return m_socket; }
const uint_t Server::gSocketClose () const [inline]
Definition at line 44 of file server.h.
References m_socket_close.
Referenced by SocketServer::Delete(), and SocketClient::Delete().
{ return m_socket_close; }
const uint_t Server::gSocketOpen () const [inline]
Definition at line 45 of file server.h.
References m_socket_open.
Referenced by SocketClient::SocketClient(), and SocketServer::SocketServer().
{ return m_socket_open; }
const string Server::gStatus () const
Definition at line 213 of file server.cpp.
{
    string output;
    return output;
}
Server::ITER (list , SocketClient * , m_socket_client_next) [private]
Referenced by ProcessInput().
const bool Server::LoadCommands ()
Definition at line 25 of file server.cpp.
References CFG_DAT_DIR_COMMAND, command_list, CSTR, Utils::CurrentTime(), Utils::DiffTime(), Utils::ListDirectory(), Command::Load(), LOGFMT, LOGSTR, m_dir_close, m_dir_open, MITER, UFLAGS_DE, UTILS_IS_FILE, and UTILS_TIME_MS.
Referenced by Startup().
{
    UFLAGS_DE( flags );
    timeval start, finish;
    Command* cmd = NULL;
    multimap<bool,string> files;
    MITER( multimap, bool,string, mi );
    start = Utils::CurrentTime();
    LOGSTR( 0, "Loading commands..." );
    // Populate the multimape with a recursive listing of the commands folder
    Utils::ListDirectory( CFG_DAT_DIR_COMMAND, true, files, m_dir_close, m_dir_open );
    if ( files.empty() )
    {
        LOGSTR( flags, "Server::LoadCommands()->Utils::ListDirectory()-> CFG_DAT_DIR_COMMAND returned NULL" );
        return false;
    }
    for ( mi = files.begin(); mi != files.end(); mi++ )
    {
        if ( mi->first == UTILS_IS_FILE )
        {
            cmd = new Command();
            if ( !cmd->Load( mi->second ) )
            {
                LOGFMT( flags, "Server::LoadCommands()->Command::Load()-> command %s returned false", CSTR( mi->second ) );
                delete cmd;
            }
        }
    }
    finish = Utils::CurrentTime();
    LOGFMT( 0, "Loaded %lu commands in %lums.", command_list.size(), Utils::DiffTime( start, finish, UTILS_TIME_MS ) );
    return true;
}
const bool Server::ProcessInput ()
Definition at line 64 of file server.cpp.
References SocketClient::Delete(), Socket::gDescriptor(), ITER(), LOGFMT, SocketClient::ProcessCommand(), socket_client_list, and UFLAGS_DE.
Referenced by Update().
{
    UFLAGS_DE( flags );
    ITER( list, SocketClient*, si );
    SocketClient* socket_client;
    sint_t client_desc = 0;
    for ( si = socket_client_list.begin(); si != socket_client_list.end(); si = m_socket_client_next )
    {
        socket_client = *si;
        m_socket_client_next = ++si;
        if ( ( client_desc = socket_client->gDescriptor() ) < 1 )
        {
            LOGFMT( flags, "Server::ProcessInput()->SocketClient::gDescriptor()-> returned invalid descriptor: %ld", client_desc );
            socket_client->Delete();
            continue;
        }
        if ( !socket_client->ProcessCommand() )
        {
            LOGFMT( flags, "Server::ProcessInput()->SocketClient::ProcessCommand()-> descriptor %ld returned false", client_desc );
            socket_client->Delete();
            continue;
        }
    }
    return true;
}
const bool Server::Running () const [inline]
Definition at line 35 of file server.h.
References m_shutdown.
Referenced by main(), SocketServer::sServer(), SocketClient::sServer(), SocketServer::Update(), and SocketClient::Update().
{ return !m_shutdown; }
const void Server::Shutdown (const sint_t & status)
Definition at line 94 of file server.cpp.
References CFG_STR_EXIT_FAILURE, CFG_STR_EXIT_SUCCESS, command_list, LOGSTR, m_shutdown, MITER, and thread_list.
Referenced by main(), SocketServer::New(), SocketClient::ProcessCommand(), Startup(), and Update().
{
    bool was_running = !m_shutdown;
    MITER( multimap, const char,Command*, mi );
    MITER( multimap, const char,Command*, mi_next );
    MITER( map, uint_t,string, ti );
    MITER( map, uint_t,string, ti_next );
    m_shutdown = true;
    // Cleanup commands
    for ( mi = command_list.begin(); mi != command_list.end(); )
    {
        mi_next = mi++;
        mi_next->second->Unload();
        command_list.erase( mi_next );
    }
    // Cleanup threads
    for ( ti = thread_list.begin(); ti != thread_list.end(); )
    {
        ti_next = ti++;
        pthread_cancel( ti_next->first );
        thread_list.erase( ti_next );
    }
    // Only output if the server actually booted; otherwise it probably faulted while getting a port from main()
    if ( was_running )
    {
        if ( status == EXIT_SUCCESS )
            LOGSTR( 0, CFG_STR_EXIT_SUCCESS );
        else
            LOGSTR( 0, CFG_STR_EXIT_FAILURE );
    }
    ::exit( status );
}
const bool Server::sPort (const uint_t & port)
Definition at line 221 of file server.cpp.
References CFG_SOC_MAX_PORTNUM, m_port, and UFLAGS_DE.
Referenced by main().
{
    UFLAGS_DE( flags );
    // No logger output; this should only be called pre-boot
    if ( port <= CFG_SOC_MIN_PORTNUM || port >= CFG_SOC_MAX_PORTNUM )
        return false;
    m_port = port;
    return true;
}
const bool Server::sSocketClose (const uint_t & amount)
Definition at line 234 of file server.cpp.
References LOGFMT, m_socket_close, UFLAGS_DE, and uintmax_t.
Referenced by SocketServer::Delete(), and SocketClient::Delete().
{
    UFLAGS_DE( flags );
    if ( amount < 1 || ( ( m_socket_close + amount ) >= uintmax_t ) )
    {
        LOGFMT( flags, "Server::sSocketClose()-> called with m_socket_close overflow: %lu + %lu", m_socket_close, amount );
        return false;
    }
    m_socket_close += amount;
    return true;
}
const bool Server::sSocketOpen (const uint_t & amount)
Definition at line 249 of file server.cpp.
References LOGFMT, m_socket_open, UFLAGS_DE, and uintmax_t.
Referenced by SocketClient::SocketClient(), and SocketServer::SocketServer().
{
    UFLAGS_DE( flags );
    if ( amount < 1 || ( ( m_socket_open + amount ) >= uintmax_t ) )
    {
        LOGFMT( flags, "Server::sSocketOpen()-> called with m_socket_open overflow: %lu + %lu", m_socket_open, amount );
        return false;
    }
    m_socket_open += amount;
    return true;
}
const void Server::Startup ()
Definition at line 131 of file server.cpp.
References CFG_STR_VERSION, Utils::CurrentTime(), LoadCommands(), LOGERRNO, LOGFMT, LOGSTR, m_port, m_shutdown, m_socket, m_time_boot, Shutdown(), SocketServer::Thread(), and UFLAGS_DE.
Referenced by main().
{
    UFLAGS_DE( flags );
    SocketServer* socket_server;
    sint_t descriptor = 0;
    m_shutdown = false;
    LOGFMT( 0, "%s started.", CFG_STR_VERSION );
    m_time_boot = Utils::CurrentTime();
    if ( ( descriptor = ::socket( AF_INET6, SOCK_STREAM, 0 ) ) < 0 )
    {
        LOGERRNO( flags, "Server::Startup()->socket()->" );
        Shutdown( EXIT_FAILURE );
    }
    socket_server = new SocketServer( this, descriptor );
    m_socket = socket_server;
    if ( !socket_server->Thread() )
    {
        LOGSTR( flags, "Server::Startup()->SocketServer::Thread()-> returned false" );
        Shutdown( EXIT_FAILURE );
    }
    // Bump ourselves to the root folder for file paths
    if ( ::chdir( ".." ) < 0 )
    {
        LOGERRNO( flags, "Server::Startup()->chdir()->" );
        Shutdown( EXIT_FAILURE );
    }
    if ( !LoadCommands() )
    {
        LOGSTR( flags, "Server::Startup()->Server::LoadCommands()-> returned false" );
        Shutdown( EXIT_FAILURE );
    }
    LOGFMT( 0, "%s is ready on port %lu.", CFG_STR_VERSION, m_port );
    LOGSTR( 0, "Last compiled on " __DATE__ " at " __TIME__ "." );
    return;
}
const void Server::Update ()
Definition at line 175 of file server.cpp.
References Utils::CurrentTime(), LOGSTR, m_time_current, ProcessInput(), Shutdown(), UFLAGS_DE, and USLEEP_MAX.
Referenced by main().
{
    UFLAGS_DE( flags );
    m_time_current = Utils::CurrentTime();
    if ( !ProcessInput() )
    {
        LOGSTR( flags, "Server::Update()->Server::ProcessInput()-> returned false" );
        Shutdown( EXIT_FAILURE );
    }
    // Sleep to control game pacing
    ::usleep( USLEEP_MAX / CFG_GAM_PULSE_RATE );
    return;
}
Member Data Documentation
uint_t Server::m_dir_close [private]
Definition at line 54 of file server.h.
Referenced by LoadCommands(), and Server().
uint_t Server::m_dir_open [private]
Definition at line 55 of file server.h.
Referenced by LoadCommands(), and Server().
uint_t Server::m_port [private]
Definition at line 56 of file server.h.
Referenced by gPort(), Server(), sPort(), and Startup().
bool Server::m_shutdown [private]
Definition at line 57 of file server.h.
Referenced by Running(), Server(), Shutdown(), and Startup().
SocketServer* Server::m_socket [private]
Definition at line 58 of file server.h.
Referenced by gSocket(), Server(), and Startup().
uint_t Server::m_socket_close [private]
Definition at line 60 of file server.h.
Referenced by gSocketClose(), Server(), and sSocketClose().
uint_t Server::m_socket_open [private]
Definition at line 61 of file server.h.
Referenced by gSocketOpen(), Server(), and sSocketOpen().
timeval Server::m_time_boot [private]
Definition at line 62 of file server.h.
Referenced by Server(), and Startup().
timeval Server::m_time_current [private]
Definition at line 63 of file server.h.
Referenced by Server(), and Update().
The documentation for this class was generated from the following files:
h/server.h
server.cpp