NAMS - Not Another MUD Server: main.cpp File Reference
main.cpp File Reference
#include "h/includes.h"
#include "h/class.h"
#include "h/server.h"
Functions
int main (const int argc, const char *argv[])
Function Documentation
int main (const int argc, const char * argv[])
Definition at line 23 of file main.cpp.
References BSET, CFG_SOC_MAX_PORTNUM, CFG_SOC_MIN_PORTNUM, CFG_SOC_PORTNUM, Utils::iNumber(), LOGFMT, Server::Running(), Server::Shutdown(), Server::sPort(), Server::Startup(), Server::Update(), and UTILS_RAW.
{
    BSET( flags, UTILS_RAW );
    Server _server;
    if ( argc > 1 )
    {
        if ( !Utils::iNumber( argv[1] ) )
        {
            LOGFMT( flags, "Usage: %s [port #]", argv[0] );
            _server.Shutdown( EXIT_FAILURE );
        }
        else if ( !_server.sPort( atoi( argv[1] ) ) )
        {
            LOGFMT( flags, "Port number must be between %d and %d.", CFG_SOC_MIN_PORTNUM, CFG_SOC_MAX_PORTNUM );
            _server.Shutdown( EXIT_FAILURE );
        }
    }
    else
        _server.sPort( CFG_SOC_PORTNUM );
    _server.Startup();
    while( _server.Running() )
        _server.Update();
    _server.Shutdown( EXIT_SUCCESS );
}