NAMS - Not Another MUD Server: Utils Namespace Reference
Utils Namespace Reference
Classes
class DeleteObject
Functions
template<class T , class U >
const string DirPath (const T &path, const U &file)
template<class T >
const string DelSpaces (const T &t)
template<class T >
const string Lower (const T &t)
template<class T >
const string Upper (const T &t)
template<class T >
const string String (const T &t)
const timeval CurrentTime ()
const uint_t DiffTime (const timeval &prev, const timeval &current, const uint_t &granularity)
const string _FormatString (const uint_t &narg, const bitset< CFG_MEM_MAX_BITSET > &flags, const string &caller, const string &fmt,...)
const string __FormatString (const uint_t &narg, const bitset< CFG_MEM_MAX_BITSET > &flags, const string &caller, const string &fmt, va_list &val)
const void _Logger (const uint_t &narg, const bitset< CFG_MEM_MAX_BITSET > &flags, const string &caller, const string &fmt,...)
const uint_t NumChar (const string &input, const string &item)
const vector< string > StrNewlines (const string &input)
const string StrTime (const timeval &now)
const vector< string > StrTokens (const string &input)
const bool iDirectory (const string &dir)
const bool iFile (const string &file)
const bool iNumber (const string &input)
template<class K , class V , class I >
const bool KeyValue (K &key, V &val, const I &item)
template<class K , class V >
const void KeySet (const bool &igncase, bool &found, const K &keyd, const V &valu, const string &item, string &loc)
template<class K , class V , class I , class L >
const void KeySet (const bool &igncase, bool &found, const K &keyd, const V &valu, const I &item, L &loc)
const multimap< bool, string > ListDirectory (const string &dir, const bool &recursive, multimap< bool, string > &output, uint_t &dir_close, uint_t &dir_open)
Function Documentation
const string Utils::__FormatString (const uint_t & narg, const bitset< CFG_MEM_MAX_BITSET > & flags, const string & caller, const string & fmt, va_list & val)
Definition at line 66 of file utils.cpp.
References CSTR, Logger, LOGSTR, NumChar(), StrTokens(), UFLAGS_DE, and UTILS_TYPE_ERROR.
Referenced by _FormatString(), and _Logger().
{
    UFLAGS_DE( uflags );
    va_list args;
    vector<string> arguments;
    vector<string>::iterator si;
    vector<char> buf;
    string output, token;
    sint_t size = 0;
    if ( fmt.empty() )
    {
        LOGSTR( uflags, "Utils::__FormatString()-> called with empty fmt" );
        return output;
    }
    arguments = StrTokens( fmt );
    for ( si = arguments.begin(); si != arguments.end(); si++ )
    {
        token = *si;
        if ( token.find( "%" ) != string::npos ) // not foolproof, but it should catch some worst cases by attempting
            size++;                              // to ensure a matching narg : format specifier count
    }
    if ( narg != 1 && narg != static_cast<uint_t>( size ) && narg != NumChar( fmt, "%" ) ) // if narg == 1 invocation was func( flags, string )
    {
        bitset<CFG_MEM_MAX_BITSET> eflags;
        eflags.set( UTILS_TYPE_ERROR );
        Logger( eflags, "Number of arguments (%lu) did not match number of format specifiers (%lu) at: %s", narg, size, CSTR( caller ) );
        return output = "";
    }
    va_copy( args, val );
    size = vsnprintf( NULL, 0, CSTR( fmt ), args );
    va_end( args );
    va_copy( args, val );
    buf.resize( size + 1 );
    vsnprintf( &buf[0], ( size + 1 ), CSTR( fmt ), args );
    va_end( args );
    return output = &buf[0];
}
const string Utils::_FormatString (const uint_t & narg, const bitset< CFG_MEM_MAX_BITSET > & flags, const string & caller, const string & fmt, ...)
Definition at line 47 of file utils.cpp.
References __FormatString(), LOGSTR, and UFLAGS_DE.
{
    UFLAGS_DE( uflags );
    va_list args;
    string output;
    if ( fmt.empty() )
    {
        LOGSTR( uflags, "Utils::_FormatString()-> called with empty fmt" );
        return output;
    }
    va_start( args, fmt );
    output = __FormatString( narg, flags, caller, fmt, args );
    va_end( args );
    return output;
}
const void Utils::_Logger (const uint_t & narg, const bitset< CFG_MEM_MAX_BITSET > & flags, const string & caller, const string & fmt, ...)
Definition at line 111 of file utils.cpp.
References __FormatString(), CurrentTime(), LOGSTR, StrTime(), UFLAGS_DE, UTILS_DEBUG, UTILS_IGNORE_CASE, UTILS_RAW, UTILS_TYPE_ERROR, UTILS_TYPE_INFO, and UTILS_TYPE_SOCKET.
{
    UFLAGS_DE( uflags );
    va_list args;
    string pre, post, output;
    uint_t i = 0;
    if ( fmt.empty() )
    {
        LOGSTR( uflags, "Utils::_Logger()-> called with empty fmt" );
        return;
    }
    va_start( args, fmt );
    output = __FormatString( narg, flags, caller, fmt, args );
    va_end( args );
    if ( output.empty() )
        return;
    // prepend timestamp
    pre = StrTime( CurrentTime() ); pre += " :: ";
    for ( i = 0; i < MAX_UTILS; i++ )
    {
        if ( flags.test( i ) )
        {
            switch( i )
            {
                case UTILS_DEBUG:       post += " ["; post += caller; post += "]"; break; // output caller
                case UTILS_IGNORE_CASE: break; // noting for now
                case UTILS_RAW:         pre.clear(); post.clear(); i = MAX_UTILS;  break; //no extraneous data applied
                case UTILS_TYPE_ERROR:  pre += CFG_STR_UTILS_ERROR;                break; // so fancy!
                case UTILS_TYPE_INFO:   pre += CFG_STR_UTILS_INFO;                 break;
                case UTILS_TYPE_SOCKET: pre += CFG_STR_UTILS_SOCKET;               break;
                default: break;
            }
        }
    }
    clog << pre << output << post << endl;
//fixme    if (!server.shutdown)
//fixme        monitor_chan(output.c_str(), MONITOR_LOG);
    return;
}
const timeval Utils::CurrentTime ()
Definition at line 22 of file utils.cpp.
References LOGERRNO, and UFLAGS_DE.
Referenced by _Logger(), Server::LoadCommands(), Server::Startup(), and Server::Update().
{
    UFLAGS_DE( flags );
    timeval now;
    if ( ::gettimeofday( &now, NULL ) < 0 )
    {
        LOGERRNO( flags, "Utils::CurrentTime()->" );
        return timeval();
    }
    return now;
}
template<class T > const string Utils::DelSpaces (const T & t) [inline]
Definition at line 48 of file utils.h.
{ string output(t); output.erase(remove_if(output.begin(), output.end(), ::isspace), output.end()); return output; }
const uint_t Utils::DiffTime (const timeval & prev, const timeval & current, const uint_t & granularity)
Definition at line 36 of file utils.cpp.
References UTILS_TIME_MS, UTILS_TIME_S, and UTILS_TIME_US.
Referenced by Server::LoadCommands().
{
    switch ( granularity )
    {
        case  UTILS_TIME_S: return ( current.tv_sec - prev.tv_sec );
        case UTILS_TIME_MS: return ( current.tv_usec - prev.tv_usec ) / 1000;
        case UTILS_TIME_US:
                   default: return ( current.tv_usec - prev.tv_usec );
    }
}
template<class T , class U > const string Utils::DirPath (const T & path, const U & file) [inline]
Definition at line 32 of file utils.h.
Referenced by Command::Load().
    {
        string output = path;
        // Ensure a trailing slash is present to properly recurse
        if ( output.compare( output.length() - 1, 1, "/" ) != 0 )
            output += "/";
        // Now append the first letter of the file recieved as a subdir
        output += file[0]; output += "/";
        // Finally add the filename
        output += file;
        return output;
    }
const bool Utils::iDirectory (const string & dir)
Definition at line 238 of file utils.cpp.
References CSTR, LOGERRNO, and UFLAGS_DE.
Referenced by ListDirectory().
{
    UFLAGS_DE( flags );
    struct stat dir_info;
    if ( ::stat( CSTR( dir ), &dir_info ) < 0 )
    {
        LOGERRNO( flags, "Utils::iDirectory()->stat()->" );
        return false;
    }
    if ( !S_ISDIR( dir_info.st_mode ) )
        return false;
    return true;
}
const bool Utils::iFile (const string & file)
Definition at line 255 of file utils.cpp.
References CSTR, LOGERRNO, and UFLAGS_DE.
Referenced by Command::Load().
{
    UFLAGS_DE( flags );
    struct stat dir_info;
    if ( ::stat( CSTR( file ), &dir_info ) < 0 )
    {
        LOGERRNO( flags, "Utils::iFile()->stat()->" );
        return false;
    }
    if ( !S_ISREG( dir_info.st_mode ) )
        return false;
    return true;
}
const bool Utils::iNumber (const string & input)
Definition at line 272 of file utils.cpp.
References LOGSTR, and UFLAGS_DE.
Referenced by main().
{
    UFLAGS_DE( flags );
    uint_t i = 0;
    if ( input.empty() )
    {
        LOGSTR( flags, "Utils::iNumber()-> called with empty input" );
        return false;
    }
    for ( i = 0; i < input.length(); i++ )
        if ( !isdigit( input[i] ) )
            return false;
    return true;
}
template<class K , class V > const void Utils::KeySet (const bool & igncase, bool & found, const K & keyd, const V & valu, const string & item, string & loc) [inline]
Definition at line 91 of file utils.h.
Referenced by Command::Load().
    {
        string key( keyd );
        string val( valu );
        if ( igncase )
        {
            transform( key.begin(), key.end(), key.begin(), ::tolower );
            transform( val.begin(), val.end(), val.begin(), ::tolower );
        }
        if( key.compare( val ) == 0 )
        {
            loc = item;
            found = true;
            return;
        }
        return;
    }
template<class K , class V , class I , class L > const void Utils::KeySet (const bool & igncase, bool & found, const K & keyd, const V & valu, const I & item, L & loc) [inline]
Definition at line 112 of file utils.h.
    {
        string key( keyd );
        string val( valu );
        if ( igncase )
        {
            transform( key.begin(), key.end(), key.begin(), ::tolower );
            transform( val.begin(), val.end(), val.begin(), ::tolower );
        }
        if( key.compare( val ) == 0 )
        {
            string tf( item );
            // Allow bools be any of: true / 1 or false / 0
            transform( tf.begin(), tf.end(), tf.begin(), ::tolower );
            if ( tf.compare( "true" ) == 0 )
                loc = true;
            else if ( tf.compare( "false" ) == 0 )
                loc = false;
            else
                stringstream( item ) >> loc;
            found = true;
            return;
        }
        return;
    }
template<class K , class V , class I > const bool Utils::KeyValue (K & key, V & val, const I & item) [inline]
Definition at line 75 of file utils.h.
Referenced by Command::Load().
    {
        size_t loc = 0;
        if ( ( loc = item.find( "=" ) ) == string::npos )
            return false;
        key = item.substr( 0, loc - 1 );
        val = item.substr( loc + 1, item.length() );
        loc = key.find_last_not_of( " " );
        key.erase( loc + 1 );
        loc = val.find_first_not_of( " " );
        val.erase( 0, loc );
        return true;
    }
const multimap< bool, string > Utils::ListDirectory (const string & dir, const bool & recursive, multimap< bool, string > & output, uint_t & dir_close, uint_t & dir_open)
Definition at line 291 of file utils.cpp.
References CSTR, iDirectory(), LOGERRNO, LOGFMT, UFLAGS_DE, UTILS_IS_DIRECTORY, and UTILS_IS_FILE.
Referenced by Server::LoadCommands().
{
    UFLAGS_DE( flags );
    DIR* directory = NULL;
    dirent* entry = NULL;
    string ifile, idir;
    if ( ( directory = ::opendir( CSTR( dir ) ) ) == NULL )
    {
        LOGFMT( flags, "Utils::OpenDirectory()->opendir()-> returned NULL for dir: %s", CSTR( dir ) );
        return output;
    }
    dir_open++;
    idir = dir;
    // Ensure a trailing slash is present to properly recurse
    if ( idir.compare( dir.length() - 1, 1, "/" ) != 0 )
        idir += "/";
    while ( ( entry = ::readdir( directory ) ) != NULL )
    {
        ifile = entry->d_name;
        // Skip over the unwanteds
        if ( ifile.compare( "." ) == 0 || ifile.compare( ".." ) == 0 )
            continue;
        if ( iDirectory( idir + ifile ) )
            output.insert( pair<bool,string>( UTILS_IS_DIRECTORY, ifile ) );
        else
            output.insert( pair<bool,string>( UTILS_IS_FILE, ifile ) );
        // Only recurse if another directory is found, otherwise a file was found, so skip it
        if ( iDirectory( idir + ifile ) && recursive )
            ListDirectory( idir + ifile, recursive, output, dir_close, dir_open );
    }
    if ( ::closedir( directory ) < 0 )
        LOGERRNO( flags, "Utils::OpenDir()->closedir()->" );
    else
        dir_close++;
    return output;
}
template<class T > const string Utils::Lower (const T & t) [inline]
Definition at line 49 of file utils.h.
{ stringstream ss; ss << nouppercase << t; return ss.str(); }
const uint_t Utils::NumChar (const string & input, const string & item)
Definition at line 159 of file utils.cpp.
References LOGSTR, and UFLAGS_DE.
Referenced by __FormatString().
{
    UFLAGS_DE( flags );
    uint_t amount = 0, i = 0;
    if ( input.empty() )
    {
        LOGSTR( flags, "Utils::NumChar()-> called with empty input" );
        return amount;
    }
    for ( i = 0; i < input.length(); i++ )
        if ( input[i] == item[0] )
            amount++;
    return amount;
}
template<class T > const string Utils::String (const T & t) [inline]
Definition at line 51 of file utils.h.
{ stringstream ss(t); return ss.str(); }
const vector< string > Utils::StrNewlines (const string & input)
Definition at line 177 of file utils.cpp.
References LOGSTR, and UFLAGS_DE.
Referenced by SocketClient::ProcessInput().
{
    UFLAGS_DE( flags );
    if ( input.empty() )
    {
        LOGSTR( flags, "Utils::StrNewlines()-> called with empty input" );
        return vector<string>();
    }
    stringstream ss( input );
    string line;
    vector<string> output;
    while ( getline( ss, line ) )
    {
        // Strip the newline off the end
        line.resize( line.length() - 1 );
        if ( !line.empty() )
            output.push_back( line );
    }
    return output;
}
const string Utils::StrTime (const timeval & now)
Definition at line 202 of file utils.cpp.
References LOGSTR, and UFLAGS_DE.
Referenced by _Logger().
{
    UFLAGS_DE( flags );
    string output;
    if ( ( output = ::ctime( &now.tv_sec ) ).empty() )
    {
        LOGSTR( flags, "Utils::CurrentTime()->ctime()-> returned NULL" );
        return output;
    }
    // Strip the newline off the end
    output.resize( output.length() - 1 );
    return output;
}
const vector< string > Utils::StrTokens (const string & input)
Definition at line 219 of file utils.cpp.
References LOGSTR, and UFLAGS_DE.
Referenced by __FormatString().
{
    UFLAGS_DE( flags );
    if ( input.empty() )
    {
        LOGSTR( flags, "Utils::StrTokens()-> called with empty input" );
        return vector<string>();
    }
    stringstream ss( input );
    istream_iterator<string> si( ss );
    istream_iterator<string> end;
    vector<string> output( si, end );
    return output;
}
template<class T > const string Utils::Upper (const T & t) [inline]
Definition at line 50 of file utils.h.
{ stringstream ss; ss << uppercase << t; return ss.str(); }